### ISSUE TITLE
Problems with replicateing the results of the ESR task

### ISSUE THREAD

**Issue by MrInformatic** [ZeweiChu/EntEval#1]
We are currently using EntEval to evaluate the performance of a model we have developed. The Tasks for the ESR tasks (WikiSRS and KORE) spearman and pearson similarity. How is the resulting score for the ESR tasks calculated from the returned values of these tasks?

**Comment by ZeweiChu** [comment]
We first apply the model to predict similarity scores. Then compute the pearson and spearman scores between model predicted scores and human scores. You may find the human predicted scores in the first columns of our corresponding dataset files.

**Comment by ZeweiChu** [comment]
The code part is here: https://github.com/ZeweiChu/EntEval/blob/master/enteval/esr.py#L144

**Comment by MrInformatic** [comment]
But how are the values in table 3 in the ESR row in the paper computed? Is it computed by taking the average of the spearman and pearson values of the tasks?

**Comment by mingdachen** [comment]
@MrInformatic I think it's the average of the spearman values of those tasks.

**Comment by MrInformatic** [comment]
Thank you, I think this answers my question.

**Comment by vardaan123** [comment]
How do you aggregate the spearman scores corresponding to Similarity and Relatedness for the WikiSRS dataset? There will be 2 spearman scores, one each for Similarity and Relatedness. Is the score reported in the paper average of all 3 scores (WikiSRS Similarity, WikiSRS Relatedness and KORE Similarity)?
