### ISSUE TITLE
Doubt in ESR task results

### ISSUE THREAD

**Issue by vardaan123** [ZeweiChu/EntEval#3]
How do you aggregate the spearman scores corresponding to Similarity and Relatedness for the WikiSRS dataset? There will be 2 spearman scores, one each for Similarity and Relatedness. Is the score reported in the paper average of all 3 scores (WikiSRS Similarity, WikiSRS Relatedness and KORE Similarity)?

**Comment by mingdachen** [comment]
Hi @vardaan123, sorry for the confusion. Yes, you're right, the score reported is the average of the three datasets (WikiSRS Similarity, WikiSRS Relatedness, and KORE).

**Comment by vardaan123** [comment]
Thanks for the clarification.
